# Generated by Django 4.1.3 on 2022-11-06 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-created'], 'verbose_name': 'Conocimiento', 'verbose_name_plural': 'Conocimientos'},
        ),
    ]
